FROM python:3.11-slim

WORKDIR /app

COPY requirements-frontend.txt .
RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY frontend ./frontend

EXPOSE 5000

CMD ["flask", "--app", "frontend.app", "run", "--host", "0.0.0.0", "--port", "5000"]
